In [1]:
import numpy as np

In [2]:
np.int8

numpy.int8

In [3]:
np.int64

numpy.int64

In [6]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [7]:
b = np.array([0, 5, 1, 1.5, 2])
b

array([0. , 5. , 1. , 1.5, 2. ])

In [9]:
a[0], a[1]

(1, 2)

In [10]:
b[[0, 2, -1]]

array([0., 1., 2.])